### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by erinc** [G4brym/django-cf#4]
I'm able to access D1 located in (Eastern NA) from Hetzner (ash-dc1 in Ashburn, VA), however any simple query is taking 3-4 seconds. Tested connecting to Western NA D1 instance from my local machine in California, it's also similary slow. Is this a known limitation?

**Comment by G4brym** [comment]
Hey @erinc yes, the D1 API is a bit slow for now.
You should try the workers-dbms engine, you just need to deploy a worker in your cloudflare account and that's it, your requests will then be much faster because they are sent via websockets
https://github.com/G4brym/django-cf?tab=readme-ov-file#using-with-durable-objects
